discord:
  -token: 'NzM3NzIzOTAwMzQyOTYwMjk4.GNfdTk.ATNNPw0oPEhnRlo76IiqMlFhtUpw-PRGHvMNII'
  -guild: 281505847799054336
  -roles:
    -role1: 471065454576795669
    -role2: 471064869781897216
    -role3: 471066065116332054
    -role4: 471066447330672640
  -channels:
    -channel1: 1066026966186201212